public class Word {
    /*
    Autorite nimed: Natali Atamanova, Aleksander Ontin
    Meie projekti nimi: Eessti-keelne-WORDLE
    Tänapäeval on erinevad mobiilimängud muutumas populaarseks ja WORDLE on üks neist.See on saadaval erinevates keeltes, kuid hetkel mitte eesti keeles. Me kavatseme selle probleemi lahendada, tehes mängu eesti keeles.
    ...
    ...
    ...
    ...
    Natali Atamanova töötas selle kallal, et saada teatud pikkusega sõnu sisaldavaid tekstifaile, mida seejärel programmis kasutada. Seejärel kirjutas ta programmi koodi.
    Aleksander Ontin oli hõivatud rühmatöö kirjeldamisega ja kommentaaride ülespanekuga. Ta kirjutas ka programmi koodi.
    ...
    ...
    ...
    ...
    */
    public static void main(String[] args) {

    }
}
